### ISSUE TITLE
When will the code released?

### ISSUE THREAD

**Issue by huihui308** [Atten4Vis/MS-DETR#1]

**Comment by ZhaoChuyang** [comment]
Hi, our paper is still under review now, we plan to release the code after reviewing.

**Comment by sdreamforchen** [comment]
> Hi, our paper is still under review now, we plan to release the code after reviewing.

您好。这个onetomany是不是推理的时候就不要了哇。谢谢

**Comment by ZhaoChuyang** [comment]
> > Hi, our paper is still under review now, we plan to release the code after reviewing.
> 
> 您好。这个onetomany是不是推理的时候就不要了哇。谢谢

是的，在 Inference 的时候不用 one-to-many 分支，只使用 one-to-one 分支

**Comment by ZhaoChuyang** [comment]
Hi, our code has been released.
