### ISSUE TITLE
could you post the training log?

### ISSUE THREAD

**Issue by jacksonsc007** [Atten4Vis/MS-DETR#5]
Thanks for your enlightening work.

I am working on your code and try to reproduce your experiments. 

Is there any chance that you post some training log for us?

**Comment by ZhaoChuyang** [comment]
Thank you for your interest, you can refer to the training log below:
[ms-detr-300-log.txt](https://github.com/Atten4Vis/MS-DETR/files/15111174/ms-detr-300.txt)
[ms-detr-pp-300-log.txt](https://github.com/Atten4Vis/MS-DETR/files/15111176/ms-detr-pp-300.txt)
[ms-detr-pp-900-log.txt](https://github.com/Atten4Vis/MS-DETR/files/15111171/ms-detr-pp-900.txt)

**Comment by jacksonsc007** [comment]
@ZhaoChuyang 
Really appreciate your help!!!
