### ISSUE TITLE
关于一对一出框

### ISSUE THREAD

**Issue by shirosy** [Atten4Vis/MS-DETR#6]
大佬好，想请问一个问题。如您展示的结果那样，一个object周围聚集着很多极其相似的query，也没有Nms操作，如何保证一对一出框呢？

**Comment by ZhaoChuyang** [comment]
你好～这些 query 的分类得分是不一样的，对于这些位置很相似的 queries，它们用 classification head 预测出的分类得分其中只会有一个很高，其他的都接近 0。
在训练阶段，一对一匹配算法选择和 ground truth 匹配的 query 时，主要也是根据分类得分的差异选择的（因为位置很相似，所以位置的得分差异不大）。在推理时得分最高的这个 query 就是最终保留的预测（对所有预测的得分取 max）。

**Comment by shirosy** [comment]
我明白了，谢谢您！
